// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package de.probst.chunkedswarm.net.netty.handler.codec.protobuf;

public final class ProtoMessages {
    private ProtoMessages() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registry.add(de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.cmd);
    }

    public interface BaseCommandOrBuilder extends
            // @@protoc_insertion_point(interface_extends:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand)
            com.google.protobuf.GeneratedMessage.
                    ExtendableMessageOrBuilder<BaseCommand> {

        /**
         * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
         */
        boolean hasType();

        /**
         * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
         */
        de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType getType();
    }

    /**
     * Protobuf type {@code de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand}
     */
    public static final class BaseCommand extends
            com.google.protobuf.GeneratedMessage.ExtendableMessage<
                    BaseCommand> implements
            // @@protoc_insertion_point(message_implements:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand)
            BaseCommandOrBuilder {
        // Use BaseCommand.newBuilder() to construct.
        private BaseCommand(com.google.protobuf.GeneratedMessage.ExtendableBuilder<de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand, ?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private BaseCommand(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final BaseCommand defaultInstance;

        public static BaseCommand getDefaultInstance() {
            return defaultInstance;
        }

        public BaseCommand getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private BaseCommand(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                                   extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType value = de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType
                                    .valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                type_ = value;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.class,
                            de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.Builder.class);
        }

        public static com.google.protobuf.Parser<BaseCommand> PARSER =
                new com.google.protobuf.AbstractParser<BaseCommand>() {
                    public BaseCommand parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new BaseCommand(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<BaseCommand> getParserForType() {
            return PARSER;
        }

        /**
         * Protobuf enum {@code de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType}
         */
        public enum CommandType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>SERIAL_MSG = 1;</code>
             */
            SERIAL_MSG(0, 1),;

            /**
             * <code>SERIAL_MSG = 1;</code>
             */
            public static final int SERIAL_MSG_VALUE = 1;


            public final int getNumber() {
                return value;
            }

            public static CommandType valueOf(int value) {
                switch (value) {
                    case 1:
                        return SERIAL_MSG;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
            internalGetValueMap() {
                return internalValueMap;
            }

            private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
                        public CommandType findValueByNumber(int number) {
                            return CommandType.valueOf(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.getDescriptor()
                                                                                                        .getEnumTypes()
                                                                                                        .get(0);
            }

            private static final CommandType[] VALUES = values();

            public static CommandType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int index;
            private final int value;

            private CommandType(int index, int value) {
                this.index = index;
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType)
        }

        private int bitField0_;
        public static final int TYPE_FIELD_NUMBER = 1;
        private de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType type_;

        /**
         * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
         */
        public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType getType() {
            return type_;
        }

        private void initFields() {
            type_ = de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType.SERIAL_MSG;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!extensionsAreInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            com.google.protobuf.GeneratedMessage
                    .ExtendableMessage<de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand>.ExtensionWriter extensionWriter =
                    newExtensionWriter();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, type_.getNumber());
            }
            extensionWriter.writeUntil(536870912, output);
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_.getNumber());
            }
            size += extensionsSerializedSize();
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseDelimitedFrom(
                java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.ExtendableBuilder<
                        de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand, Builder> implements
                // @@protoc_insertion_point(builder_implements:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand)
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommandOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.class,
                                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.Builder.class);
            }

            // Construct using de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                type_ = de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType.SERIAL_MSG;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_descriptor;
            }

            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand getDefaultInstanceForType() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.getDefaultInstance();
            }

            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand build() {
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand buildPartial() {
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand result = new de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand) {
                    return mergeFrom((de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand other) {
                if (other ==
                    de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.getDefaultInstance())
                    return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                this.mergeExtensionFields(other);
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasType()) {

                    return false;
                }
                if (!extensionsAreInitialized()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand) e
                            .getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType type_ = de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType.SERIAL_MSG;

            /**
             * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
             */
            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType getType() {
                return type_;
            }

            /**
             * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
             */
            public Builder setType(de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand.CommandType type = 1;</code>
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand.CommandType.SERIAL_MSG;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand)
        }

        static {
            defaultInstance = new BaseCommand(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand)
    }

    public interface SerializableMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bytes payload = 1;</code>
         */
        boolean hasPayload();

        /**
         * <code>required bytes payload = 1;</code>
         */
        com.google.protobuf.ByteString getPayload();
    }

    /**
     * Protobuf type {@code de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg}
     */
    public static final class SerializableMsg extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg)
            SerializableMsgOrBuilder {
        // Use SerializableMsg.newBuilder() to construct.
        private SerializableMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private SerializableMsg(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final SerializableMsg defaultInstance;

        public static SerializableMsg getDefaultInstance() {
            return defaultInstance;
        }

        public SerializableMsg getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SerializableMsg(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                                   extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            payload_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.class,
                            de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.Builder.class);
        }

        public static com.google.protobuf.Parser<SerializableMsg> PARSER =
                new com.google.protobuf.AbstractParser<SerializableMsg>() {
                    public SerializableMsg parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SerializableMsg(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<SerializableMsg> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int PAYLOAD_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString payload_;

        /**
         * <code>required bytes payload = 1;</code>
         */
        public boolean hasPayload() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bytes payload = 1;</code>
         */
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        private void initFields() {
            payload_ = com.google.protobuf.ByteString.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasPayload()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, payload_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, payload_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseDelimitedFrom(
                java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg)
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.class,
                                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.Builder.class);
            }

            // Construct using de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                payload_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_descriptor;
            }

            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg getDefaultInstanceForType() {
                return de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.getDefaultInstance();
            }

            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg build() {
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg buildPartial() {
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg result = new de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.payload_ = payload_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg) {
                    return mergeFrom((de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg other) {
                if (other ==
                    de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.getDefaultInstance())
                    return this;
                if (other.hasPayload()) {
                    setPayload(other.getPayload());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasPayload()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg) e
                            .getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes payload = 1;</code>
             */
            public boolean hasPayload() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bytes payload = 1;</code>
             */
            public com.google.protobuf.ByteString getPayload() {
                return payload_;
            }

            /**
             * <code>required bytes payload = 1;</code>
             */
            public Builder setPayload(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                payload_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes payload = 1;</code>
             */
            public Builder clearPayload() {
                bitField0_ = (bitField0_ & ~0x00000001);
                payload_ = getDefaultInstance().getPayload();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg)
        }

        static {
            defaultInstance = new SerializableMsg(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:de.probst.chunkedswarm.net.netty.handler.codec.protobuf.SerializableMsg)
        public static final int CMD_FIELD_NUMBER = 101;
        /**
         * <code>extend .de.probst.chunkedswarm.net.netty.handler.codec.protobuf.BaseCommand { ... }</code>
         */
        public static final
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.BaseCommand,
                de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg> cmd = com.google.protobuf.GeneratedMessage
                .newMessageScopedGeneratedExtension(
                        de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.getDefaultInstance(),
                        0,
                        de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.class,
                        de.probst.chunkedswarm.net.netty.handler.codec.protobuf.ProtoMessages.SerializableMsg.getDefaultInstance());
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tmsg.proto\0227de.probst.chunkedswarm.net." +
                "netty.handler.codec.protobuf\"\226\001\n\013BaseCom" +
                "mand\022^\n\004type\030\001 \002(\0162P.de.probst.chunkedsw" +
                "arm.net.netty.handler.codec.protobuf.Bas" +
                "eCommand.CommandType\"\035\n\013CommandType\022\016\n\nS" +
                "ERIAL_MSG\020\001*\010\010d\020\200\200\200\200\002\"\300\001\n\017SerializableMs" +
                "g\022\017\n\007payload\030\001 \002(\0142\233\001\n\003cmd\022D.de.probst.c" +
                "hunkedswarm.net.netty.handler.codec.prot" +
                "obuf.BaseCommand\030e \001(\0132H.de.probst.chunk" +
                "edswarm.net.netty.handler.codec.protobuf",
                ".SerializableMsgBH\n7de.probst.chunkedswa" +
                "rm.net.netty.handler.codec.protobufB\rPro" +
                "toMessages"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                                                new com.google.protobuf.Descriptors.FileDescriptor[]{
                                                }, assigner);
        internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_BaseCommand_descriptor,
                new java.lang.String[]{"Type",});
        internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_de_probst_chunkedswarm_net_netty_handler_codec_protobuf_SerializableMsg_descriptor,
                new java.lang.String[]{"Payload",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
